---
role_name_check: 0
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
platforms:
  - name: ec2-rockylinux9
    type: ec2
    image: ami-093bd987f8e53e1f2
    region: us-west-2
    vpc_id: vpc-07bd460b98a3fb162
    vpc_subnet_id: subnet-0725b4ef4d069f1bf
    instance_type: t3.micro
    hostvars:
      test_hostvar: test
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/create.yml
    prepare: prepare.yml
    converge: converge.yml
    side_effect: ../resourcs/side_effect.yml
    verify: ../resources/verify.yml
    cleanup: ../resources/cleanup.yml
    destroy: ../resources/destroy.yml
  config_options:
    defaults:
      gathering: explicit
      playbook_vars_root: top
      verbosity: ${ANSIBLE_VERBOSITY:-0}
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
  enabled: true

