---
# Collect information about EC2 instances that's needed by Molecule later
#
# Expected input variables:
#  - __influxdb1x_platform_instance: The instance configuration, as returned by amazon.aws.ec2_instance_info
#
# Output:
#  - influxdb1x_platform_instance_configs: A list of dictionaries, each containing the instance config
#                           needed by the `platform` role to write Molecule instance configuration
#

- name: Discover | Collect EC2 instance data
  loop: "{{ __influxdb1x_platforms }}"
  loop_control:
    loop_var: __influxdb1x_platform
    label: "{{ __influxdb1x_platform.name }}"
  amazon.aws.ec2_instance_info:
    profile: "{{ __influxdb1x_platform.aws_profile | default(omit) }}"
    access_key: "{{ __influxdb1x_platform.aws_access_key_id | default(omit) }}"
    secret_key: "{{ __influxdb1x_platform.aws_secret_access_key | default(omit) }}"
    session_token: "{{ __influxdb1x_platform.aws_session_token | default(omit) }}"
    region: "{{ __influxdb1x_platform.region }}"
    filters:
      "tag:ClusterID": "{{ __influxdb1x_platform.cluster_id }}"
      "tag:molecule-run-id": "{{ __influxdb1x_platform.internal_id }}"
      instance-state-name:
        - pending
        - running
        - stopping
        - stopped
        - shutting-down
  register: __influxdb1x_platform_ec2_instances

- name: Discover | 🐜 | Show AWS instance data
  ansible.builtin.debug:
    var: __influxdb1x_platform_ec2_instances
    verbosity: 1

- name: Discover | Store instance configuration
  loop: "{{ __influxdb1x_platform_ec2_instances.results }}"
  loop_control:
    loop_var: __influxdb1x_platform_instance_result
    label: "{{ __influxdb1x_platform_instance_result.__influxdb1x_platform.name }}"
  vars:
    __influxdb1x_platform: "{{ __influxdb1x_platform_instance_result.__influxdb1x_platform }}"
    __influxdb1x_platform_hostvars: >-
      {%- set __influxdb1x_platform_instances = [] -%}
      {%- for __influxdb1x_platform_instance in __influxdb1x_platform_instance_result.instances -%}
        {%- set __influxdb1x_tag_hostvars = {} -%}
        {%- for __influxdb1x_hostvar_mapping in __influxdb1x_platform.tag_hostvar_mappings | default({}) | dict2items -%}
          {%- set _ = __influxdb1x_tag_hostvars.update({
            __influxdb1x_hostvar_mapping.value: __influxdb1x_platform_instance.tags[__influxdb1x_hostvar_mapping.key]
          }) -%}
        {%- endfor -%}
        {%- set _ = __influxdb1x_platform_instances.append({
          'instance': __influxdb1x_platform_instance_result.__influxdb1x_platform.name,
          'hostname': __influxdb1x_platform_instance.tags.Name | default('unnamed'),
          'ansible_host': __influxdb1x_platform_instance.public_ip_address,
          'ansible_port': __influxdb1x_platform.ssh_port,
          'ansible_user': __influxdb1x_platform.ssh_user,
          'ansible_ssh_private_key_file': __influxdb1x_platform.private_key_runtime_path,
          'ec2_instance_id': __influxdb1x_platform_instance.instance_id
        } | combine(__influxdb1x_tag_hostvars)) -%}
      {%- endfor -%}
      {{ __influxdb1x_platform_instances }}
  ansible.builtin.set_fact:
    __influxdb1x_platform_instance_configs: >-
      {{
        __influxdb1x_platform_instance_configs | default([]) + __influxdb1x_platform_hostvars
      }}

- name: Discover | 🐜 | Show instance configuration
  ansible.builtin.debug:
    var: __influxdb1x_platform_instance_configs
    verbosity: 1

