---
# Remove InfluxDB 1.x platform

- name: Deprovision | Remove InfluxDB 1.x cluster
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/remove_cluster.yml"

- name: Deprovision | Ephemeral AWS Security group does not exist
  loop: >-
    {{
      __influxdb1x_platforms
      | selectattr('enable_aws_config', 'eq', true)
      | selectattr('security_group_type', 'eq', 'ephemeral')
    }}
  loop_control:
    loop_var: __influxdb1x_platform_cfg
    label: "{{ __influxdb1x_platform_cfg.name }}"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/remove_aws_sg.yml"

- name: Deprovision | Run config does not exist
  ansible.builtin.file:
    path: "{{ influxdb1x_platform_run_config_path }}"
    state: absent

