---
# Load information about this InfluxDB cluster

- name: An existing cluster is defined
  when:
    - __influxdb1x_platform.cluster_id is defined
    - __influxdb1x_platform.cluster_id | length > 0
  vars:
    __influxdb1x_platform_existing_clusters: "{{ influxdb1x_platforms | selectattr('cluster_id', 'truthy') | list }}"
  block:
    - name: Load cluster configuration from orchestrator
      loop: "{{ influxdb1x_platforms }}"
      loop_control:
        loop_var: __influxdb1x_platform
        label: "{{ influxdb1x_platform.name }}"
      ansible.builtin.uri:
        url: "{{ influxdb1x_platform_url }}/clusters/{{ __influxdb1x_platform.cluster_id }}"
        method: GET
        return_content: true
        body_format: json
        user: "{{ influxdb1x_platform_api_creds.username }}"
        password: "{{ influxdb1x_platform_api_creds.password }}"
        status_code:
          - 200
          - 404
      register: __influxdb1x_platform_cluster_info_queries

    - name: Cluster configuration not found
      loop: "{{ __influxdb1x_platform_cluster_info_queries.results | selectattr('status', 'eq', 404) | list }}"
      loop_control:
        loop_var: __influxdb1x_platform_cluster_info_record
        label: "{{ __influxdb1x_platform_cluster_info_record.__influxdb1x_platform.name }}"
      ansible.builtin.assert:
        that:
          - __influxdb1x_platform_cluster_info_record.message == "Cluster ID not found"
        fail_msg: Unhandled error loading cluster configuration! {{ __influxdb1x_platform_cluster_info_record }}
        success_msg: Cluster ID is not found

    - name: Parse cluster configuration
      loop: "{{ __influxdb1x_platform_cluster_info_queries.results | selectattr('status', 'eq', 200) | list }}"
      loop_control:
        loop_var: __influxdb1x_platform_cluster_info_record
        label: "{{ __influxdb1x_platform_cluster_info_record.__influxdb1x_platform.name }}"
      ansible.builtin.set_fact:
        __influxdb1x_platform_cluster_info: "{{ __influxdb1x_platform_cluster_info | default([]) +
          [__influxdb1x_platform_cluster_info_record.json] }}"

    - name: Export cluster ID
      when: __influxdb1x_platform_cluster_info | default([]) | length > 0
      loop: "{{ __influxdb1x_platform_cluster_info }}"
      loop_control:
        loop_var: __influxdb1x_platform_cluster_detail
        label: "{{ __influxdb1x_platform_cluster_detail.id }}"
      vars:
        __influxdb1x_platform_name: "{{ __influxdb1x_platform_cluster_detail.__influxdb1x_platform_cluster_info_record.name }}"
      ansible.builtin.set_fact:
        __influxdb1x_platform_cluster_id_mapping: "{{ __influxdb1x_platform_cluster_info | default({}) | combine({
          __influxdb1x_platform_cluster_detail.id: __influxdb1x_platform_cluster_detail
          }, recursive=true) }}"

