---
# Update EC2 instances for accessiblity by Molecule

- name: Search for existing EC2 instances
  amazon.aws.ec2_instance_info:
    profile: "{{ __influxdb1x_platform_cfg.aws_profile | default(omit) }}"
    region: "{{ __influxdb1x_platform_cfg.region }}"
    filters:
      "tag:molecule-run-id": "{{ influxdb1x_platform_run_config.run_id }}"
  register: __influxdb1x_platform_existing_ec2_instances

- name: Validate returned EC2 instances
  ansible.builtin.assert:
    that:
      - __influxdb1x_platform_existing_ec2_instances.instances | length > 0
    fail_msg: "No existing EC2 instances found for Molecule run ID: {{ influxdb1x_platform_run_config.run_id }}"
    success_msg: "Found existing EC2 instances for Molecule run ID: {{ influxdb1x_platform_run_config.run_id }}"

- name: Modify EC2 instances
  vars:
    __influxdb1x_platform_ec2_instances: "{{ __influxdb1x_platform_existing_ec2_instances if __influxdb1x_platform_new_ec2_instances.skipped |
      default(false) else __influxdb1x_platform_new_ec2_instances }}"
  block:
    - name: Show target ec2 instances
      ansible.builtin.debug:
        var: __influxdb1x_platform_ec2_instances
        verbosity: 2

    - name: Show existing security groups for instance 0
      ansible.builtin.debug:
        var: __influxdb1x_platform_ec2_instances.instances[0].security_groups | map(attribute='group_id') | list
        verbosity: 1

    # NOTE: This assumes that all cluster members have the same security groups!
    - name: Add Molecule access security group to hosts
      loop: "{{ __influxdb1x_platform_ec2_instances.instances }}"
      loop_control:
        loop_var: __influxdb1x_platform_instance
        label: "{{ __influxdb1x_platform_instance.instance_id }}"
      vars:
        __influxdb1x_platform_ec2_current_security_groups: "{{ __influxdb1x_platform_ec2_instance.security_groups | map(attribute='group_id') | list }}"
        __influxdb1x_platform_cfg: "{{ influxdb1x_platforms
          | selectattr('cluster_id', 'defined')
          | selectattr('cluster_id', 'equalto', __influxdb1x_platform_instance.tags.ClusterID)
          | list | first }}"
        __influxdb1x_platform_molecule_security_groups: "{{ __influxdb1x_platform_cfg.security_groups or [__influxdb1x_platform_cfg.security_group_name] }}"
      amazon.aws.ec2_instance:
        profile: "{{ __influxdb1x_platform_cfg.aws_profile | default(omit) }}"
        instance_ids: "{{ __influxdb1x_platform_ec2_instances.instances | map(attribute='instance_id') | list }}"
        security_groups: "{{ __influxdb1x_platform_molecule_security_groups + __influxdb1x_platform_ec2_current_security_groups }}"
        state: running

