---
# Update EC2 instances for accessiblity by Molecule
#
# Expected input variables:
#  __influxdb1x_platform: The platform configuration to update
#  __influxdb1x_platform_ec2_instance_data: The list of EC2 instances to update, including platform configuration
#

- name: Modify EC2 | DEBUG | Show platform configuration
  ansible.builtin.debug:
    var: __influxdb1x_platform
    verbosity: 1

- name: Modify EC2 | DEBUG | Show EC2 instance data
  ansible.builtin.debug:
    var: __influxdb1x_platform_ec2_instance_data
    verbosity: 1

- name: Modify EC2 | Configure EC2 instance
  loop: "{{ __influxdb1x_platform_ec2_instance_data }}"
  loop_control:
    loop_var: __influxdb1x_platform_ec2_instance
    label: "{{ __influxdb1x_platform_ec2_instance.instance_id }}"
  vars:
    __influxdb1x_platform_ec2_current_security_groups: >-
      {{ __influxdb1x_platform_ec2_instance.security_groups | map(attribute='group_id') | list }}
    __influxdb1x_platform_sensitive: "{{ __influxdb1x_platforms_sensitive | selectattr('name', 'eq', __influxdb1x_platform.name) | first }}"
  amazon.aws.ec2_instance:
    profile: "{{ __influxdb1x_platform.aws_profile | default(omit) }}"
    access_key: "{{ __influxdb1x_platform.aws_access_key_id | default(omit) }}"
    secret_key: "{{ __influxdb1x_platform_sensitive.aws_secret_access_key | default(omit) }}"
    session_token: "{{ __influxdb1x_platform_sensitive.aws_session_token | default(omit) }}"
    region: "{{ __influxdb1x_platform.cluster_config.region }}"
    instance_ids: "{{ [__influxdb1x_platform_ec2_instance.instance_id] }}"
    security_groups: >-
      {{
        (__influxdb1x_platform_ec2_current_security_groups
        + [__influxdb1x_platform.ephemeral_security_group_id])
        | unique
      }}
    state: "{{ influxdb1x_platform_desired_ec2_instance_state | default(__influxdb1x_platform.aws_ec2_desired_instance_state, true) }}"
  register: __influxdb1x_platform_ec2_instance_update_async
  async: 60
  poll: 0
  changed_when: false

- name: Modify EC2 | Instance configuration is complete
  loop: "{{ __influxdb1x_platform_ec2_instance_update_async.results }}"
  loop_control:
    loop_var: __influxdb1x_platform_ec2_instance_update
    label: "{{ __influxdb1x_platform_ec2_instance_update.__influxdb1x_platform_ec2_instance.instance_id }}"
  ansible.builtin.async_status:
    jid: "{{ __influxdb1x_platform_ec2_instance_update.ansible_job_id }}"
  register: __influxdb1x_platform_ec2_instance_update_status
  until: __influxdb1x_platform_ec2_instance_update_status.finished
  retries: 20
  delay: 5
# TODO: Add 'changed_when' field with relevant condition for ec2 instance changes

- name: Modify EC2 | Clean up async cache
  loop: "{{ __influxdb1x_platform_ec2_instance_update_status.results }}"
  loop_control:
    loop_var: __influxdb1x_platform_ec2_instance_update
    label: "{{ __influxdb1x_platform_ec2_instance_update.instance_ids | first }}"
  ansible.builtin.async_status:
    jid: "{{ __influxdb1x_platform_ec2_instance_update.ansible_job_id }}"
    mode: cleanup

