---
# Provision InfluxDB 1.x platform
#

- name: Provision | Write run config to file
  vars:
    __influxdb1x_platform_config_content:
      platforms: "{{ __influxdb1x_platforms }}"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/write_config.yml"

- name: Provision | Create InfluxDB 1.x cluster
  vars:
    # TODO: Var with list of all platforms where a cluster doesn't exist
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_cluster.yml"

- name: Provision | Ephemeral AWS security group exists
  loop: >-
    {{
      __influxdb1x_platforms
      | selectattr('enable_aws_config', 'eq', true)
      | selectattr('security_group_type', 'eq', 'ephemeral')
    }}
  loop_control:
    loop_var: __influxdb1x_platform_cfg
    label: "{{ __influxdb1x_platform_cfg.name }}"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_aws_sg.yml"

