---
# Remove a cluster managed by a centralised orchestrator

- name: Remove any clusters that exist
  vars:
    __influxdb1x_fated_platforms: >-
      {{
        __influxdb1x_platforms | selectattr('cluster_id', 'defined')
        | selectattr('cluster_id', 'truthy')
      }}
  block:
    - name: Destroy | 🐜 DEBUG | Show fated platforms
      loop: "{{ __influxdb1x_fated_platforms }}"
      loop_control:
        loop_var: __influxdb1x_platform
        label: "{{ __influxdb1x_platform.name }}"
      ansible.builtin.debug:
        var: __influxdb1x_platform
        verbosity: 1

    - name: Destroy | Deprovision InfluxDB 1.x Enterprise cluster
      loop: "{{ __influxdb1x_fated_platforms }}"
      loop_control:
        loop_var: __influxdb1x_platform
        label: "{{ __influxdb1x_platform.name }}"
      vars:
        __influxdb1x_platform_sensitive: >-
          {{
            __influxdb1x_platforms_sensitive | selectattr('name', 'eq', __influxdb1x_platform.name) | first
          }}
      ansible.builtin.uri:
        url: "{{ __influxdb1x_orchestrator_api_url }}/clusters/{{ __influxdb1x_platform.cluster_id }}"
        body_format: json
        body:
          machines_status: "{{ __influxdb1x_platform.destroyed_machines_status }}"
        method: PATCH
        user: "{{ __influxdb1x_platform.orchestrator_username }}"
        password: "{{ __influxdb1x_platform_sensitive.orchestrator_password }}"
        status_code:
          - 204
          - 422
      register: __influxdb1x_platform_cluster_destruction_orchestrator_responses

    - name: Destroy | DEBUG | Show cluster destruction responses
      ansible.builtin.debug:
        var: __influxdb1x_platform_cluster_destruction_orchestrator_responses
        verbosity: 1

    - name: Destroy | Wait for cluster destruction to complete
      loop: "{{ __influxdb1x_fated_platforms }}"
      loop_control:
        loop_var: __influxdb1x_platform
        label: "{{ __influxdb1x_platform.name }}"
      vars:
        __influxdb1x_platform_sensitive: >-
          {{
            __influxdb1x_platforms_sensitive | selectattr('name', 'eq', __influxdb1x_platform.name) | first
          }}
      ansible.builtin.uri:
        url: "{{ __influxdb1x_orchestrator_api_url }}/clusters/{{ __influxdb1x_platform.cluster_id }}"
        method: GET
        user: "{{ __influxdb1x_platform.orchestrator_username }}"
        password: "{{ __influxdb1x_platform_sensitive.orchestrator_password }}"
        return_content: true
      register: __influxdb1x_platform_cluster_destruction_status
      until: __influxdb1x_platform_cluster_destruction_status.json.machines_status == __influxdb1x_platform.destroyed_machines_status
      retries: "{{ (__influxdb1x_platform.destruction_timeout | int / 10) | int }}"
      delay: 10
      async: "{{ __influxdb1x_platform.destruction_timeout | int + 10 }}"

#- name: Remove ssh key file
#  ansible.builtin.file:
#    path: "{{ __influxdb1x_platform_cfg.private_key_path }}"
#    state: absent


