---
# tasks file for potato_platform

- name: 🐞 Show potato_platform_definition
  ansible.builtin.debug:
    var: potato_platform_definition
    verbosity: 1

- name: Generate runtime configuration (potato_platform role)
  ansible.builtin.set_fact:
    __potato_platform_cfg: "{{ potato_platform_defaults | combine(potato_platform_definition | default({})) }}"

- name: Generate runtime configuration (Potato InfluxDB cluster creation)
  ansible.builtin.set_fact:
    __potato_platform_potato_cluster_cfg: "{{ potato_platform_creation_request_defaults |
                                          combine(__potato_platform_cfg.influxdb_cluster_cfg | default({})) }}"

- name: 🦋 Show potato_platform
  ansible.builtin.debug:
    var: __potato_platform_cfg
    verbosity: 1

- name: Platform is deployed
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_cluster.yml"
  when: potato_platform_state == 'present'

- name: Platform is not deployed
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/remove_cluster.yml"
  when: potato_platform_state == 'absent'

