---
# Make sure everything is 👌

- name: Validate Potato connection configuration
  ansible.builtin.asssert:
    that:
      - potato_platform_domain is string and potato_platform_domain | length > 0
      - potato_platform_url is string and potato_platform_url | length > 0 and potato_platform_url | regex_search('http[s]?://')
      - potato_platform_api_creds is mapping
      - potato_platform_api_creds.username is string and potato_platform_api_creds.username | length > 0
      - potato_platform_api_creds.password is string and potato_platform_api_creds.password | length > 0
    fail_msg: "Potato connection configuration is invalid"
    success_msg: "Potato connection configuration is valid"

- name: Validate platform configuration - {{ potato_platform.name | default('invalid') }}
  ansible.builtin.assert:
    that:
      - potato_platform is mapping
      - potato_platform.name is string and potato_platform.name | length > 0
      - potato_platform.region is string and potato_platform.region | length > 0
      - potato_platform.vpc_id is string
      - potato_platform.vpc_subnet_id is string and potato_platform.vpc_subnet_id | length > 0
      - potato_platform.security_groups is defined
      - potato_platform.security_group_name is string and potato_platform.security_group_name | length > 0
      - potato_platform.security_group_description is string and potato_platform.security_group_description | length > 0
      - potato_platform.security_group_rules is sequence
      - potato_platform.security_group_rules_egress is sequence
      - potato_platform.tags is mapping
      - potato_platform.key_name is string and potato_platform.key_name | length > 0
      - potato_platform.private_key_path is string and potato_platform.private_key_path | length > 0
      - potato_platform.public_key_path is string and potato_platform.public_key_path | length > 0
      - potato_platform_creation_request_body is mapping
      - potato_platform_default_ssh_source_key_path is string and potato_platform_default_ssh_source_key_path | length > 0
      - potato_platform_creation_timeout is integer and potato_platform_creation_timeout >= 0
      - potato_platform_default_boot_wait_seconds is integer and potato_platform_default_boot_wait_seconds >= 0
    fail_msg: "Platform configuration is invalid"
    success_msg: "Platform configuration is valid"

