---
# Make sure everything is 👌

- name: Validate Potato connection configuration
  ansible.builtin.assert:
    that:
      - potato_platform_potato_address is string and potato_platform_potato_address | length > 0
      - potato_platform_url is string and potato_platform_url | length > 0 and potato_platform_url | regex_search('http[s]?://')
      - potato_platform_api_creds is mapping
      - potato_platform_api_creds.username is string and potato_platform_api_creds.username | length > 0
      - potato_platform_api_creds.password is string and potato_platform_api_creds.password | length > 0
    fail_msg: "Potato connection configuration is invalid"
    success_msg: "Potato connection configuration is valid"

- name: Validate platform configuration - {{ potato_platform.name | default('invalid') }}
  ansible.builtin.assert:
    that:
      - __potato_platform_cfg is mapping
      - __potato_platform_cfg.name is string and __potato_platform_cfg.name | length > 0
      - __potato_platform_cfg.region is string and __potato_platform_cfg.region | length > 0
      - __potato_platform_cfg.vpc_id is string
      - ((__potato_platform_cfg.vpc_subnet_id is string and __potato_platform_cfg.vpc_subnet_id | length > 0) if
        __potato_platform_cfg.vpc_id is not defined else true)
      - __potato_platform_cfg.security_groups is defined
      - __potato_platform_cfg.security_group_name is string and __potato_platform_cfg.security_group_name | length > 0
      - __potato_platform_cfg.security_group_description is string and __potato_platform_cfg.security_group_description | length > 0
      - __potato_platform_cfg.security_group_rules is sequence
      - __potato_platform_cfg.security_group_rules_egress is sequence
      - __potato_platform_cfg.tags is mapping
      - __potato_platform_cfg.private_key_path is string and __potato_platform_cfg.private_key_path | length > 0
      - __potato_platform_cfg.public_key_path is string and __potato_platform_cfg.public_key_path | length > 0
      - __potato_platform_potato_cluster_cfg is mapping and __potato_platform_potato_cluster_cfg | length > 0
      - __potato_platform_cfg.private_key_source_path is string and __potato_platform_cfg.private_key_source_path | length > 0
      - __potato_platform_cfg.creation_timeout is integer and __potato_platform_cfg.creation_timeout >= 0
      - __potato_platform_cfg.boot_wait_seconds is integer and __potato_platform_cfg.boot_wait_seconds >= 0
    fail_msg: "Platform configuration is invalid"
    success_msg: "Platform configuration is valid"

