---
# Remove deployed resources

- name: Show platform configuration
  ansible.builtin.debug:
    var: platform_config
    verbosity: 1

- name: Show runtime platform configuration
  ansible.builtin.debug:
    var: __platform_config
    verbosity: 1

- name: Initialize state
  ansible.builtin.set_fact:
    # Number of times this role has been included during this playbook run
    __platform_run_count: "{{ __platform_run_count | default(0) | int + 1 }}"

- name: Remove {{ __platform_config | length }} Molecule platform(s)
  loop: "{{ __platform_config | map(attribute='type') | unique | list }}"
  loop_control:
    loop_var: __platform_type
    label: "{{ __platform_type }}"
  vars:
    platform_target_state: absent
    __platform_is_fq: "{{ __platform_type | regex_search('^\\w+\\.\\w+\\.\\w+$') is truthy }}"
    __platform_collection_name: >-
      {{ __platform_type.split('.')[:-1] | join('.') if __platform_is_fq else ansible_collection_name }}
    __platform_type_short: >-
      {{ __platform_type.split('.')[-1] if __platform_is_fq else __platform_type }}
  ansible.builtin.include_role:
    name: "{{ __platform_collection_name }}.{{ __platform_type_short }}_platform"
