---
# Remove deployed resources

- name: Show platform configuration
  ansible.builtin.debug:
    var: platform_config
    verbosity: 1

- name: Show runtime platform configuration
  ansible.builtin.debug:
    var: __platform_config
    verbosity: 1

- name: Initialize state
  ansible.builtin.set_fact:
    # Number of times this role has been included during this playbook run
    __platform_run_count: "{{ __platform_run_count | default(0) | int + 1 }}"

- name: Remove {{ __platform_config | length }} Molecule platform(s)
  vars:
    __platform_type: "{{ __platform_config | map(attribute='type') | first }}"
    platform_target_config: "{{ __platform_config }}"
    platform_target_state: absent
  ansible.builtin.include_role:
    name: "{{ ansible_collection_name }}.{{ __platform_type }}_platform"

#- name: Remove docker-type platform
#  when: platform_type == 'docker'
#  ansible.builtin.include_role:
#    name: "{{ ansible_collection_name }}.docker_platform"
#  vars:
#    docker_platform_name: "{{ platform_name }}"
#    docker_platform_state: absent
#
#- name: Remove ec2-type platform
#  when: platform_type == 'ec2'
#  ansible.builtin.include_role:
#    name: "{{ ansible_collection_name }}.ec2_platform"
#  vars:
#    ec2_platform_name: "{{ platform_name }}"
#    ec2_platform_state: absent
#    ec2_platform_definition: "{{ platform_molecule_cfg }}"

