---
role_name_check: 0
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
platforms:
  - name: influxdb1x-platform-test
    type: influxdb_1x
    vpc_id: vpc-07bd460b98a3fb162
    region: us-west-2
    orchestrator_address: https://potato.a.influxcloud.us
    private_key_source_path: /home/syndr@styx.ultroncore.net/.ssh/cloud1-dev-potato
    ssh_user: core
    ssh_port: 22
    cluster_config:
      config_tag: 1.11.6.1-staging-pro
      init: latest
      password: ku4kQePLTI6RBYtq0KuY
      username: test-ci-admin
    ignore_machines_status: true
    creation_timeout: 240
    hostvars: {}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/create.yml
    prepare: prepare.yml
    converge: converge.yml
    side_effect: ../resourcs/side_effect.yml
    verify: verify.yml
    cleanup: ../resources/cleanup.yml
    destroy: ../resources/destroy.yml
  config_options:
    defaults:
      gathering: explicit
      playbook_vars_root: top
      verbosity: ${ANSIBLE_VERBOSITY:-0}
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
  enabled: true

