---
role_name_check: 0
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
platforms:
  - name: influxdb1x-platform-defaults
    type: influxdb_1x
    ssh_port: 22
    cluster_config:
      ami: ami-09e3a3301cb1777b9
      config_tag: 1.11.6.1-staging-pro
      init: latest
      region: us-east-1
    hostvars: {}
  - name: influxdb1x-platform-timeout
    type: influxdb_1x
    ssh_port: 22
    ignore_machines_status: true
    creation_timeout: 300
    cluster_config:
      ami: ami-09e3a3301cb1777b9
      config_tag: 1.11.6.1-staging-pro
      init: latest
      region: us-east-1
    hostvars: {}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/create.yml
    prepare: prepare.yml
    converge: converge.yml
    side_effect: ../resourcs/side_effect.yml
    verify: verify.yml
    cleanup: ../resources/cleanup.yml
    destroy: ../resources/destroy.yml
  config_options:
    defaults:
      gathering: explicit
      playbook_vars_root: top
      verbosity: ${ANSIBLE_VERBOSITY:-0}
  env:
    ARA_API_CLIENT: ${ARA_API_CLIENT:-'http'}
    ARA_API_SERVER: ${ARA_API_SERVER:-'http://localhost:8000'}
    ARA_DEFAULT_LABELS: ${ARA_DEFAULT_LABELS:-'testing,molecule'}
    # To use Ara with molecule:
    #  export the ANSIBLE_CALLBACK_PLUGINS env var with the output of 'python3 -m ara.setup.callback_plugins'
    ANSIBLE_CALLBACK_PLUGINS: ${ANSIBLE_CALLBACK_PLUGINS}
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
  enabled: true

