---
# Build a custom image based upon the provided image, running Systemd as PID 1.
#
# Expected variables:
#   - __docker_platform_config_custom: The desired Molecule platform configurations requiring custom entrypoint configuration for systemd
#   - docker_platform_modify_image_buildpath: The path to the build directory for the custom image
#

- name: Exec Systemd | Build path exists
  ansible.builtin.file:
    path: "{{ docker_platform_modify_image_buildpath }}"
    state: directory
    mode: 0755

- name: Exec Systemd | Build file exists
  loop:
    - bash.service.j2
    - entrypoint.sh.j2
    - Dockerfile.j2
  loop_control:
    loop_var: __docker_platform_item
  ansible.builtin.template:
    src: templates/{{ __docker_platform_item }}
    dest: "{{ docker_platform_modify_image_buildpath}}/{{ __docker_platform_item | regex_replace('\\.j2$', '') }}"

- name: Exec Systemd | Launch image build
  loop: "{{ __docker_platform_config_custom }}"
  loop_control:
    loop_var: __docker_platform_definition
    label: "{{ __docker_platform_definition.name }}"
  vars:
    __docker_platform_built_image_name: "molecule-local-build/{{ __docker_platform_definition.image | split(':') | first | split('/') | last }}-custom"
  community.docker.docker_image:
    name: "{{ __docker_platform_built_image_name }}"
    build:
      path: "{{ docker_platform_modify_image_buildpath }}"
      cache_from: "{{ __docker_platform_definition.image }}"
    source: build
    force_source: true    # Always build a new image when this is run
    tag: latest
  register: __docker_platform_image_build_tasks
  async: 600
  poll: 0

- name: 🐜 Exec Systemd | Show image build job tasks
  ansible.builtin.debug:
    var: __docker_platform_image_build_tasks
    verbosity: 1

- name: Exec Systemd | Wait for image build to complete
  ansible.builtin.async_status:
    jid: "{{ __docker_platform_image_build_tasks.ansible_job_id }}"
  register: __docker_platform_image_build_result
  until: __docker_platform_image_build_result.finished
  retries: 60
  delay: 10

- name: Exec Systemd | Clean up async cache
  ansible.builtin.async_status:
    jid: "{{ __docker_platform_image_build_tasks.ansible_job_id }}"
    mode: cleanup

- name: Exec Systemd | Show image build details
  ansible.builtin.debug:
    var: __docker_platform_image_build_result
    verbosity: 1

