---
# vars file for init

# Assume that we are not operating in a monolith to start
__init_monolith: false

# The project types supported by this role
__init_supported_project_types:
  - collection
  - role
  - monolith

# The platform types supported by this role
__init_supported_platform_types:
  - docker
  - ec2

# The platforms to be configured by this role
__init_runtime_platforms: "{{ init_platforms | combine(init_platforms_defaults) }}"

